### ISSUE TITLE
How to hide and unhide OS-level window (X11)?

### ISSUE THREAD

**Issue by diovudau** [pplux/imgui-app#4]
Hello,

I want to hide and unhide the complete program window. The program is controlled through an external MIDI controller which sends the signals to hide and show. I am personally on X11 where this is called Unmap() and Map(), but other OSes need something else of course.

sokol.h has private functions to do this:  `_SOKOL_PRIVATE void _sapp_x11_show_window(void)` and `_SOKOL_PRIVATE void _sapp_x11_hide_window(void)`. 

I want to avoid editing sokol.h and imgui.h. Any recommendation for a best practise how to extend imgui-app here?

**Comment by diovudau** [comment]
I tried to read all the code and I don't think it is possible without changing sokol.h and imgui_app.cpp . 

Is there some kind of hacky C or C++ magic to access these functions anyway? 
```
_SOKOL_PRIVATE bool _sapp_x11_window_visible(void)
_SOKOL_PRIVATE void _sapp_x11_show_window(void)
_SOKOL_PRIVATE void _sapp_x11_hide_window(void)
```

**Comment by pplux** [comment]
We can expose them, let me look into those :)
