### ISSUE TITLE
When trying to drag window with touch interface (WASM on mobile) get stuck in moving window state

### ISSUE THREAD

**Issue by Xadiant** [pplux/imgui-app#7]
I compiled using emscripten (latest pre-compiled release as of today) with the example app in the main readme for imgui-app.  I then hosted the resulting html/wasm/js and tested on my mobile phone.  

When I give the top of an imgui window a series of taps, it then glues to my finger and I can move it, however, all subsequent taps move the window to the new tap's location and there is no way to stop tat from happening save from restarting the application (refreshing the page).

This does not happen on the live imgui emscripten example: https://www.dearimgui.org/webdemo/master/example_emscripten.html

Any tips on how to fix this?  I don't mind working on a fix and submitting a pull request if I can figure this out.

**Comment by pplux** [comment]
this must be a sokol issue somehow, I haven't test it so I can't provide that much info.  Have you looked into sokol repo to see if the issue comes from event handling there?

**Comment by Xadiant** [comment]
Ah I see, I initially thought thought the events were handled in this repo for some reason.  Ill close this for now, and update here if I find a workaround.

**Comment by Xadiant** [comment]
Here is the issue as observed highly detailed as an issue on the sokol page: https://github.com/floooh/sokol/issues/759

Includes video of problem, and my attempted work-arounds so far.

**Comment by Xadiant** [comment]
See the pull request to fix in sokol, this is a simple change anybody can make themselves int he meantime: https://github.com/floooh/sokol/pull/760

**Comment by floooh** [comment]
I just merged the fix. Many thanks again for the investigation and PR, @Xadiant!
